export default {
  title: 'light',
  colors: {
    green: '#32B768',
    green_dark: '#2B7A4B',
    green_light: '#DAF2E4',
    heading: '#52665A',
    text: '#738078',
    text_light: '#AAB2AD',
    background: '#ffffff',
    body_home: '#FFFFFF',
    shape: '#F0F0F0',
    white: '#FFFFFF',
    gray: '#738078',
    blue: '#3D7199',
    blue_light: '#EBF6FF',
    red: '#E83F5B',
    background_controller: '#FFFFFF',
    overlay: 'rgba(21,21,21,0.5)',
  },
  fonts: {
    text: 'Jost_400Regular',
    heading: 'Jost_600SemiBold',
    complement: 'Jost_400Regular',
  },
};
